### ISSUE TITLE
Repo owner still alive?

### ISSUE THREAD

**Issue by testman42** [HawaiinPizza/Ross-Scott-and-the-quest-for-the-holy-GUI-#12]
@HawaiinPizza you still alive my dude? Are you in the Matrix chat? There were some good ideas / developments in there.

Also, if you look at the [shared document](https://pad.riseup.net/p/GUI-keep), someone came up with a very good acronym that more or less solidified the chosen name of the project: **Rational Operating System Shell** (ROSS)
so while `https://github.com/HawaiinPizza/rational-operating-system-shell` would still be long URL, it would be shorter and more understandable than current repo name. Although it would not be a reference to Monty Python (how many people today still know of Monty Python sketches?), it still does have some humour in it.

Would you maybe mind giving all the existing contributors full access to this repo?

**Comment by HawaiinPizza** [comment]
I know this is going to sound super lazy, but I'm still alive. Finals week was this week, and I have to do a bunch of essays.
In terms of the matrix chat, I thought we migrated to the discord. However, Friday I should be done with finals and I can stop being lazy
