### ISSUE TITLE
Live chat and collaborative document

### ISSUE THREAD

**Issue by bfeber** [HawaiinPizza/Ross-Scott-and-the-quest-for-the-holy-GUI-#5]
To talk about the project I suggest an open live chat service like Matrix/Riot and a collaborative document on for example Etherpad where we can collect ideas.
I created both here:
https://pad.riseup.net/p/GUI-keep
https://riot.im/app/#/room/#gui:matrix.org
We can use another (preferrably open) chat platform if you want.

**Comment by LongJohn-Silver** [comment]
I tried joining the chat but it seems it is dead? It would be nice if it could be revived or something

**Comment by bfeber** [comment]
> I tried joining the chat but it seems it is dead? It would be nice if it could be revived or something

Thank you for noticing, I updated the link.
