### ISSUE TITLE
Microsoft and its quest for WinUI 3.0

### ISSUE THREAD

**Issue by Altair-Qu-Ten** [HawaiinPizza/Ross-Scott-and-the-quest-for-the-holy-GUI-#7]
I'm sure some of the people here have heard about it, but if you're not familiar:

Windows' UI framework has been missing/broken for a long time now, which is why all the different programs you use on Windows all have their own look to their Windows.
Currently [MS is developing WinUI 3.0](https://github.com/microsoft/microsoft-ui-xaml), which will mean that prgrammers don't have to fiddle around with developing their Windows and GUI elements from scratch.

I'm bringing this up, because, I think, it could help our endeavor towards the **holy GUI**. Maybe there is a chance to actually team up with them? I have no idea, but a lot of hope.

**Comment by HawaiinPizza** [comment]
I think it can be done independently of the group. Right now we're making **the best** program launcher for Unix, and if it's successful, we can port it to Windows.

**Comment by arawnx** [comment]
This looks more like a tool for designing UIs within traditional UWP applications than it does a way to render novel graphics in userland. So far, we're planning to start development for a radial menu and eventually mouse gesture middleware on Linux, so this is more of a backburner project.

**Comment by Altair-Qu-Ten** [comment]
Makes sense, but couldn't the framework eventually be used for a Win port? I'd imagine utilizing these tools would prove practical eventuallly...

**Comment by arawnx** [comment]
Am I mistaken that it's for designing UIs _within_ conventional windowed applications? If that's the case, it couldn't support this use case. If it's able to do either windowless or transparent-window rendering, then it may become practical.

**Comment by Altair-Qu-Ten** [comment]
I'm not too deep into the whole topic, but I don't think that this is on their roadmap, in which case you'd be right, although you could still have a classic Window for configuration in a simple, if not fully intuitive way.

**Comment by arawnx** [comment]
The issue is that, as of now, Windows is very restrictive in terms of rendering; whereas on Linux we can kind of do whatever we want, on Windows we have to create a dedicated window and we're only allowed to render within that space. This works well for desktop applications, but it'd cause trouble with a system-wide utility like we're trying to get at here. This may change in the near future, but I don't expect Microsoft to be very hasty about it.
